using ProjectGenerator.Annotations;

namespace ProjectGenerator.Tests;

[DbEntity, Model]
public interface ISimpleThing
{
    [PrimaryKey]
    [AutogeneratedKey]
    public int Id { get; }
    public string Value { get; }
}