using System.ComponentModel.DataAnnotations;

namespace ProjectGenerator.Annotations;

public class NotInDbAttribute : System.Attribute { }
public class OnlyInDbAttribute : System.Attribute { }

public class DbEntityAttribute : System.Attribute { }
public class AutogeneratedKeyAttribute : System.Attribute { }
public class ModelAttribute : System.Attribute { }
public class ReadOnlyAttribute : System.Attribute { }
public class PrimaryKeyAttribute : System.Attribute {
    public bool IsAutogonerated = true;
    public bool IsOptional = false;
    public PrimaryKeyAttribute(bool isAutogenerated = true, bool isOptional = false)
    {
        IsAutogonerated = isAutogenerated;
        IsOptional = isOptional;
    }
}
public class OptionalAttribute : System.Attribute { }
public class CommentSummaryAttribute : System.Attribute 
{
    public string Text { get; set; }
    public CommentSummaryAttribute (string text)
    {
        Text = text;
    }
}
public class ControllerFromHeaderAttribute : System.Attribute
{
    public string HeaderName { get; set; }
    public ControllerFromHeaderAttribute(string headerName)
    {
        HeaderName = headerName;
    }
}
