using System.Text;

namespace ProjectGenerator;

public class CommandsGenerator : GeneratorBase
{
    //generates commands for service layer
    //create, update, delete

    public void Generate(DataModel dm)
    {
        Directory.CreateDirectory($"{dm.BasePath}Services\\Commands");

        foreach (var cls in dm.Classes.Values.Where(e => e.IsModel))
        {
            GenerateCommand(dm, cls, "createModel", "Create");
            GenerateCommand(dm, cls, "updateModel", "Update");
            GenerateCommand(dm, cls, "deleteModel", "Delete");
        }
    }

    public void GenerateCommand(DataModel dm, Class cls, string crudAction, string namePrefix)
    {
        var sb = new IndentingStringBuilder();
        sb.AppendLine($"using {dm.OutputNamespace}.Models;");    //to potentially reuse base models. Only some generated project will need this using, we can add some conditional logic later.
        sb.AppendLine();
        sb.AppendLine($"namespace {dm.OutputNamespace}.Commands;");
        sb.AppendLine();
        sb.AppendLine($"public partial class {namePrefix}{cls.Name}Command");
        GenerateFields(cls.Fields, sb, crudAction, CommandCreateFields);
        File.WriteAllText($"{dm.BasePath}Services\\Commands\\{namePrefix}{cls.Name}Command.cs", sb.ToString());
    }

    void CommandCreateFields(IndentingStringBuilder sb, IEnumerable<Field> fields)
    {
        var fromHeaders = fields.Where(e => e.ControllerFromHeader != null);
        foreach (var fromHeader in fromHeaders)
        {
            sb.AppendLine($"public {fromHeader.TypeName} {fromHeader.ControllerFromHeader} {{ get; set; }}");
        }
    }

    public override bool ShouldGenerateField(Field field, string action)
    {
        if (field.IsOnlyInDb) return false;
        if (field.IsReadOnly && action == "updateModel") return false;
        //if (field.IsPrimaryKey() && field.PrimaryKey.IsAutogenerated) return false;
        if (field.ControllerFromHeader != null) return false;
        if (field.IsPrimaryKey() && field.PrimaryKey.IsAutogenerated && action == "createModel") return false;
        if (field.IsPrimaryKey() && field.ControllerFromHeader != null && action == "createModel") return false;
        if (field.IsPrimaryKey() && field.ControllerFromHeader != null && action == "updateModel") return false;
        if (field.IsPrimaryKey() && field.ControllerFromHeader != null && action == "deleteModel") return false;
        if (action == "deleteModel" && !field.IsPrimaryKey()) return false;
        return true;
    }
}
