using System.Text;

namespace ProjectGenerator;

public class ModelsGenerator : GeneratorBase
{
    //generates models for controllers that come from REST API
    //create, update, delete

    public void Generate(DataModel dm)
    {
        Directory.CreateDirectory($"{dm.BasePath}Controllers\\Models");
        foreach (var cls in dm.Classes.Values.Where(e => e.IsModel))
        {
            var sb = new IndentingStringBuilder();
            sb.AppendLine($"namespace {dm.OutputNamespace}.Models;");
            sb.AppendLine();
            GenerateXmlCommentSummary(cls, sb);
            sb.AppendLine($"public class {cls.Name}Model");
            GenerateFields(cls.Fields, sb, "model");
            File.WriteAllText($"{dm.BasePath}Controllers\\Models\\{cls.Name}Model.cs", sb.ToString());

            sb = new IndentingStringBuilder();
            sb.AppendLine($"namespace {dm.OutputNamespace}.Models;");
            sb.AppendLine();
            //GenerateXmlCommentSummary(cls, sb);
            //GenerateXmlComment("summary", $"{cls.Name} to be created", sb);
            sb.AppendLine($"public class Create{cls.Name}Model");
            GenerateFields(cls.Fields, sb, "createModel");
            File.WriteAllText($"{dm.BasePath}Controllers\\Models\\Create{cls.Name}Model.cs", sb.ToString());

            sb = new IndentingStringBuilder();
            sb.AppendLine($"namespace {dm.OutputNamespace}.Models;");
            sb.AppendLine();
            GenerateXmlCommentSummary(cls, sb);
            sb.AppendLine($"public class Update{cls.Name}Model");
            GenerateFields(cls.Fields, sb, "updateModel");
            File.WriteAllText($"{dm.BasePath}Controllers\\Models\\Update{cls.Name}Model.cs", sb.ToString());
        }
    }

    public override bool ShouldGenerateField(Field field, string action)
    {
        if (field.IsOnlyInDb) return false;
        if (field.IsReadOnly && action == "updateModel") return false;
        if (field.IsPrimaryKey() && field.PrimaryKey.IsAutogenerated && action == "createModel") return false;
        if (field.IsPrimaryKey() && field.ControllerFromHeader != null && action == "createModel") return false;
        if (field.IsPrimaryKey() && action == "updateModel") return false;
        return true;
    }
}
