using System.Text;
using System.Xml.Linq;

namespace ProjectGenerator;

public class ServicesGenerator : GeneratorBase
{
    //generates services

    public void Generate(DataModel dataModel)
    {
        foreach (var cls in dataModel.Classes.Values.Where(e => e.IsModel))
        {
            var serviceName = $"{cls.Name}Service";
            var repositoryName = $"_{Utils.LowerCaseFirst(cls.Name)}Repository";
            var pkField = cls.PrimaryKeyField();
            var pkFieldVarName = Utils.LowerCaseFirst(pkField.Name);
            var sb = new IndentingStringBuilder();

            sb.AppendLine($"using {Program.GeneratedProjectNamespace}.Infrastructure;");
            sb.AppendLine($"using {Program.GeneratedProjectNamespace}.Repositories;");
            sb.AppendLine($"using {Program.GeneratedProjectNamespace}.Commands;");
            sb.AppendLine($"using {Program.GeneratedProjectNamespace}.Interfaces;");
            sb.AppendLine($"using {Program.GeneratedProjectNamespace}.Entities;");
            sb.AppendLine($"using {Program.GeneratedProjectNamespace}.Models;");
            sb.AppendLine($"using IOTA.Core.Security;");
            

            sb.AppendLine($"namespace {Program.GeneratedProjectNamespace}.Services;");
            sb.AppendLine();

            sb.AppendLine($"public class {serviceName}: I{serviceName}");
            sb.IncreaseIndent();
            sb.AppendLine($"private readonly I{cls.Name}Repository {repositoryName};");
            sb.AppendLine($"private readonly IUnitOfWork _unitOfWork;");
            sb.AppendLine($"private readonly IUsers _users;");
            sb.AppendLine($"");
            sb.AppendLine($"public {serviceName}(I{cls.Name}Repository {repositoryName.Substring(1)}, IUnitOfWork unitOfWork, IUsers users)");
            sb.IncreaseIndent();
            sb.AppendLine($"{repositoryName} = {repositoryName.Substring(1)};");
            sb.AppendLine($"_unitOfWork = unitOfWork;");
            sb.AppendLine($"_users = users;");
            sb.DecreaseIndent();
            sb.AppendLine($"");

            ///////////////GET
            sb.AppendLine($"async Task<{cls.Name}Model> I{serviceName}.Get({pkField.TypeName} {pkFieldVarName})");
            sb.IncreaseIndent();
            sb.AppendLine($"var entity = await {repositoryName}.Get({pkFieldVarName});");
            sb.AppendLine($"if (entity == null) throw new NotFoundException(\"{cls.Name} with given name not found\");");
            sb.AppendLine($"var model = new {cls.Name}Model");
            sb.IncreaseIndent();
            foreach (var field in cls.Fields.Where(e => !e.IsPrimaryKey && !e.IsOnlyInDb))
            {
                sb.AppendLine($"{field.Name} = entity.{field.Name},");
            }
            sb.DecreaseIndent(";");
            sb.AppendLine($"return model;");
            sb.DecreaseIndent();
            sb.AppendLine();

            ///////////////CREATE
            sb.AppendLine($"async Task<{pkField.TypeName}> I{serviceName}.Create(Create{cls.Name}Command command)");
            sb.IncreaseIndent();
            sb.AppendLine("//TODO EnsurePermissionAndAccess(...) ");
            if (!pkField.IsAutogeneratedKey)
            {
                sb.AppendLine($"var found = await {repositoryName}.Get(command.{pkField.Name});");
                sb.AppendLine($"if (found != null) throw new InvalidStateException(\"{cls.Name} with given {pkField.Name} already exists\");");
            }
            sb.AppendLine($"var entity = new {cls.Name}");
            sb.IncreaseIndent();
            foreach (var field in cls.Fields.Where(e => (!e.IsPrimaryKey || !e.IsAutogeneratedKey) && !e.IsOnlyInDb))
            {
                sb.AppendLine($"{field.Name} = command.{field.Name},");
            }
            sb.DecreaseIndent(";");
            sb.AppendLine($"{repositoryName}.Save(entity);");
            sb.AppendLine($"_unitOfWork.SaveChanges();");
            sb.AppendLine($"return entity.{pkField.Name};");
            sb.DecreaseIndent();
            sb.AppendLine();
            ////////////UPDATE
            /*
            async Task<bool> IUserSettingDefaultsService.Update(UpdateUserSettingDefaultCommand command)
            {
                var entity = await _userSettingDefaultsRepository.GetUserSettingDefaultByNameForUpdate(command.Name);
                if (entity == null) throw new NotFoundException("User setting default with given name does not exist");

                entity.Value = command.NewValue;

                await _unitOfWork.SaveChanges();
                return true;
            }
             */
            sb.AppendLine($"async Task I{serviceName}.Update(Update{cls.Name}Command command)");
            sb.IncreaseIndent();
            sb.AppendLine($"var entity = await {repositoryName}.GetForUpdate(command.{pkField.Name});");
            sb.AppendLine($"if (entity == null) throw new NotFoundException(\"{cls.Name} with given {pkField.Name} does not exist\");");
            foreach (var field in cls.Fields.Where(e => !e.IsPrimaryKey && !e.IsOnlyInDb))
            {
                sb.AppendLine($"entity.{field.Name} = command.{field.Name};");
            }
            sb.AppendLine($"_unitOfWork.SaveChanges();");
            sb.DecreaseIndent();
            sb.AppendLine();

            ////////////////DELETE
            sb.AppendLine($"async Task I{serviceName}.Delete(Delete{cls.Name}Command command)");
            sb.IncreaseIndent();
            sb.AppendLine($"var entity = await {repositoryName}.Get(command.{pkField.Name});");
            sb.AppendLine($"if (entity == null) throw new NotFoundException(\"{cls.Name} with given {pkField.Name} does not exist\");");
            sb.AppendLine($"{repositoryName}.Delete(entity);");
            sb.AppendLine($"_unitOfWork.SaveChanges();");
            sb.DecreaseIndent();
            sb.AppendLine();
            sb.DecreaseIndent();

            Directory.CreateDirectory($"{Program.BasePath}Services\\Interfaces");
            File.WriteAllText($"{Program.BasePath}Services\\{cls.Name}Service.g.cs", sb.ToString());

            sb = new IndentingStringBuilder();
            sb.AppendLine($"using {Program.GeneratedProjectNamespace}.Models;");
            sb.AppendLine($"using {Program.GeneratedProjectNamespace}.Commands;");
            sb.AppendLine();
            sb.AppendLine($"namespace {Program.GeneratedProjectNamespace}.Services;");
            sb.AppendLine();
            sb.AppendLine($"public interface I{serviceName}");
            sb.IncreaseIndent();
            sb.AppendLine($"Task<{cls.Name}Model> Get({pkField.TypeName} {pkFieldVarName});");
            sb.AppendLine($"Task<{pkField.TypeName}> Create(Create{cls.Name}Command command);");
            sb.AppendLine($"Task Update(Update{cls.Name}Command command);");
            sb.AppendLine($"Task Delete(Delete{cls.Name}Command command);");
            sb.DecreaseIndent();
            File.WriteAllText($"{Program.BasePath}Services\\Interfaces\\I{cls.Name}Service.g.cs", sb.ToString());
        }
    }

    public override bool ShouldGenerateField(Field field, string action)
    {
        if (field.IsOnlyInDb) return false;
        if (field.IsOnlyCreate && action == "updateModel") return false;
        if (field.IsPrimaryKey && action == "createModel") return false;
        if (field.IsPrimaryKey && action == "updateModel") return false;
        return true;
    }
}
