using ProjectGenerator.Annotations;

namespace ProjectGenerator.InputInterfaces;

//public interface IHasName
//{
//    public string Name { get; }
//}

//public interface IHasId
//{
//    [CommentSummary("Entity ID")]
//    [PrimaryKey, AutogeneratedKey]
//    public int Id { get; }
//}

[DbEntity, Model]
public interface IUserSettingDefault
{
    [PrimaryKey]
    public string Name { get; }
    public string Value { get; }
}

[DbEntity, Model]
public interface IUserSetting
{
    [PrimaryKey]
    public string Name { get; }

    [PrimaryKey]
    [ControllerFromHeader("Authorization")]
    public string UserId { get; }
    public string Value { get; }
}

//[CommentSummary("Object type")]
//[DbEntity, Model]
//public interface IObjectType : IHasId, IHasName
//{
//    public string AuditCorrelationId { get; }
//    [OnlyInDb]
//    public ICollection<IAttributeDefinitionObjectType> AttributeDefinitionObjectTypes { get; set; }

//    //[NotInDb]
//    //public ICollection<IAttributeDefinition> AttributeDefinitions { get; set; }
//    //[NotInDb]
//    //public ICollection<int> AttributeDefinitionIds { get; set; }
//}

//[DbEntity]
//public interface IAttributeDefinitionObjectType
//{
//    [PrimaryKey]
//    public IAttributeDefinition AttributeDefinition { get; }
//    [PrimaryKey]
//    public IObjectType ObjectType { get; }
//    public string AuditCorrelationId { get; set; }
//}

//[DbEntity, Model]
//public interface IAttributeDefinition : IHasId, IHasName
//{
//    [OnlyCreate]
//    public string Type { get; set; }
//}
