using ProjectGenerator.Annotations;

namespace ProjectGenerator.InputInterfaces;

//public interface IHasName
//{
//    public string Name { get; }
//}

//public interface IHasId
//{
//    [CommentSummary("Entity ID")]
//    [PrimaryKey, AutogeneratedKey]
//    public int Id { get; }
//}

[DbEntity, Model]
public interface IConfiguration
{
    [PrimaryKey(IsAutogonerated = false)]
    //[CommentSummary("Configuration key")]
    public string Key { get; }

    [PrimaryKey(IsAutogonerated = false, IsOptional = true)]
    //[CommentSummary("Name of service. Optional. Null means shared configuration for all services.")]
    public string ServiceName { get; }

    //[CommentSummary("Configuration value")]
    public string Value { get; }

    //[CommentSummary("Flag, if given configuration value should be encrypted.")]
    public bool Encrypted { get; }  //questionable

    [ControllerFromHeader("AuditCorrelationId")]
    [OnlyInDb]
    public string AuditCorrelationId { get; }
}

//[DbEntity, Model]
//public interface IUserSettingDefault
//{
//    [PrimaryKey]
//    public string Name { get; }
//    public string Value { get; }
//}

[DbEntity, Model]
public interface IUserSetting
{
    [PrimaryKey(IsAutogonerated = false)]
    public string Name { get; }

    [PrimaryKey(IsAutogonerated = false)]
    [ControllerFromHeader("Authorization")]
    public string UserId { get; }
    public string Value { get; }
}

//[CommentSummary("Object type")]
//[DbEntity, Model]
//public interface IObjectType : IHasId, IHasName
//{
//    public string AuditCorrelationId { get; }
//    [OnlyInDb]
//    public ICollection<IAttributeDefinitionObjectType> AttributeDefinitionObjectTypes { get; set; }

//    //[NotInDb]
//    //public ICollection<IAttributeDefinition> AttributeDefinitions { get; set; }
//    //[NotInDb]
//    //public ICollection<int> AttributeDefinitionIds { get; set; }
//}

//[DbEntity]
//public interface IAttributeDefinitionObjectType
//{
//    [PrimaryKey]
//    public IAttributeDefinition AttributeDefinition { get; }
//    [PrimaryKey]
//    public IObjectType ObjectType { get; }
//    public string AuditCorrelationId { get; set; }
//}

//[DbEntity, Model]
//public interface IAttributeDefinition : IHasId, IHasName
//{
//    [OnlyCreate]
//    public string Type { get; set; }
//}
